
services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: almossar
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql
